
name: "CIS macos 11 CI workflow"

on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 * * 0' #At 00:00 on Sunday every week



jobs:

  CIS-macos-latest-job:
      name: "macos-latest CIS_Apple_macOS_11.0_Big_Sur_Benchmark_v2.0.0 "
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
      - name: "1.1 Verify all Apple-provided software is current (Automated)"
        run: |
          # Description:
          # Software	updates	should	be	run	at	minimum	every	30	days
          sudo defaults read /Library/Preferences/com.apple.SoftwareUpdate | grep -e LastFullSuccessfulDate.
          # Audit:
          # Run	the	following	command	to	verify there	are	no	software	updates
          sudo softwareupdate -l
          # Remediation:
          # Run	the	following	command	to	verify	what	packages	need	to	be	installed:
          sudo softwareupdate -l
          # Run	the	following	command	to	install	all	the	packages	that	need	to	be	updated
          sudo softwareupdate -i -a
          # run	the	following	command	to	install	individual	packages
          # sudo softwareupdate -i '<package name>'

  CIS-macos-11-job:
      name: "macos-11 CIS_Apple_macOS_11.0_Big_Sur_Benchmark_v2.0.0"
      runs-on: macos-11
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
      - name: "1.1 Verify all Apple-provided software is current (Automated)"
        run: |
          # Description:
          # Software	updates	should	be	run	at	minimum	every	30	days
          sudo defaults read /Library/Preferences/com.apple.SoftwareUpdate | grep -e LastFullSuccessfulDate.
          # Audit:
          # Run	the	following	command	to	verify there	are	no	software	updates
          sudo softwareupdate -l
          # Remediation:
          # Run	the	following	command	to	verify	what	packages	need	to	be	installed:
          sudo softwareupdate -l
          # Run	the	following	command	to	install	all	the	packages	that	need	to	be	updated
          sudo softwareupdate -i -a
          # run	the	following	command	to	install	individual	packages
          # sudo softwareupdate -i '<package name>'

