
name: "macos packages CI workflow"

on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 * * 0' #At 00:00 on Sunday every week



jobs:

  macos-latest-snmp:
      name: "snmp - macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
      - name: "enable SNMP"
        run: |
          # Create a backup of the default SNMP configuration file
          sudo mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.orig
          cat /etc/snmp/snmpd.conf.orig 
          cat <<EOT | sudo tee /etc/snmp/snmpd.conf
          com2sec local     localhost       COMMUNITY
          com2sec mynetwork NETWORK/24      COMMUNITY
          rocommunity public default .1
          # We limit unauthenticated requesters to the system contact info
          # rocommunity  public default .1.3.6.1.2.1.1.4 
          EOT
          # Enable the SNMP daemon
          sudo launchctl load -w /System/Library/LaunchDaemons/org.net-snmp.snmpd.plist


  macos-latest-ncpa:
      name: "ncpa - macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
        # https://assets.nagios.com/downloads/ncpa/docs/Installing-NCPA.pdf
      - name: "Installing ancpa"
        run: |
          curl -L -o ncpa-2.2.1.dmg https://assets.nagios.com/downloads/ncpa/ncpa-2.2.1.dmg           


              


  macos-latest-virtualenv-ncpa:
      name: "ncpa virtualenv - macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
      - name: "check on docker version"
        run: docker version         
      - name: "Installing ncpa"
        run: |
          # python -V
          python3 -V
          # pip --version
          pip3 --version
          # which pip
          which pip3
          # pip install --upgrade pip
          python3 -m pip install --upgrade pip
          # python3 -m pip install --user ansible 
          python3 -m virtualenv ncpa  # Create a virtualenv if one does not already exist
          source ncpa/bin/activate   # Activate the virtual environment
          curl -L -o ncpa-2.2.1.dmg https://assets.nagios.com/downloads/ncpa/ncpa-2.2.1.dmg



  # macos-110:
  #     name: "macos-11.0"
  #     runs-on: macos-11.0 # ProductVersion 11.0.1
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update    
  #     - name: "install osquery"
  #       run: |
  #           chmod +x scripts/install_osquery.sh
  #           sh scripts/install_osquery.sh 
  #     - name: "DFIR osquery list"
  #       run: |
  #           chmod +x scripts/dfir_osquery.sh
  #           sh scripts/dfir_osquery.sh          
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list --formula"
  #       run: brew list --formula #List all the installed formulas
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           


  # macos-1015:
  #     name: "macos-10.15"
  #     runs-on: macos-10.15 # ProductVersion 10.15.7
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update     
  #     - name: "install osquery"
  #       run: |
  #           chmod +x scripts/install_osquery.sh
  #           sh scripts/install_osquery.sh 
  #     - name: "DFIR osquery list"
  #       run: |
  #           chmod +x scripts/dfir_osquery.sh
  #           sh scripts/dfir_osquery.sh         
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list --formula"
  #       run: brew list --formula #List all the installed formulas
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           
