
name: "macos pip ansible CI workflow"

on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 * * 0' #At 00:00 on Sunday every week



jobs:

  macos-latest-ansible:
      name: "ansible - macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
      - name: "Installing and upgrading Ansible with pip"
        run: |
          python -V
          python3 -V
          pip --version
          which pip
          pip install --upgrade pip
          python -m pip install --user ansible  
          # echo $PATH          
          # export PATH=/opt/local/bin:/opt/local/sbin:$PATH  
          pip show ansible #Version: 4.4.0
          # ansible --version  #ansible: command not found 
          which ansible               


              


  macos-latest-virtualenv-ansible:
      name: "ansible virtualenv - macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version 
      - name: "Installing and upgrading Ansible with pip"
        run: |
          # python -V
          python3 -V
          # pip --version
          pip3 --version
          # which pip
          which pip3
          # pip install --upgrade pip
          python3 -m pip install --upgrade pip
          python3 -m pip install --user ansible 
          python3 -m virtualenv ansible  # Create a virtualenv if one does not already exist
          source ansible/bin/activate   # Activate the virtual environment
          python3 -m pip install ansible
          pip show ansible #Version: 4.4.0
          asdf reshim python3
          which ansible
          # ansible --version



  # macos-110:
  #     name: "macos-11.0"
  #     runs-on: macos-11.0 # ProductVersion 11.0.1
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update    
  #     - name: "install osquery"
  #       run: |
  #           chmod +x scripts/install_osquery.sh
  #           sh scripts/install_osquery.sh 
  #     - name: "DFIR osquery list"
  #       run: |
  #           chmod +x scripts/dfir_osquery.sh
  #           sh scripts/dfir_osquery.sh          
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list --formula"
  #       run: brew list --formula #List all the installed formulas
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           


  # macos-1015:
  #     name: "macos-10.15"
  #     runs-on: macos-10.15 # ProductVersion 10.15.7
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: "brew update"
  #       run: brew update     
  #     - name: "install osquery"
  #       run: |
  #           chmod +x scripts/install_osquery.sh
  #           sh scripts/install_osquery.sh 
  #     - name: "DFIR osquery list"
  #       run: |
  #           chmod +x scripts/dfir_osquery.sh
  #           sh scripts/dfir_osquery.sh         
  #     - name: "check on brew version"
  #       run: brew --version   #Homebrew 2.5.12   
  #     - name: "brew cask list"
  #       run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #     - name: "brew list --formula"
  #       run: brew list --formula #List all the installed formulas
  #     - name: "Get OS X System Version"
  #       run: sw_vers       
  #     - name: "Get Mac System Details with system_profiler"
  #       run: system_profiler | more  
  #     - name: "osfingerprinting"
  #       run: uname -a                           
